draw:
  name: Draw
  description: Generate a picture
  fields:
    payload:
      name: Payload
      description: List of drawing commands
      required: true
      example: |
        - type: text
          value: Hello World!
          x: 5
          y: 5
          size: 40
      selector:
        object:
    rotate:
      name: Rotate
      description: "Picture rotation in degrees (0, 90, 180, 270), default: 0"
      required: false
      example: '0'
      default: 0
      selector:
        number:
          min: 0
          max: 270
          step: 90
    width:
      name: Width
      description: Width of picture in pixels
      required: true
      example: 400
      selector:
        number:
          min: 10
          max: 4096
          step: 1
    height:
      name: Height
      description: Height of picture in pixels
      required: true
      example: 240
      selector:
        number:
          min: 10
          max: 4096
          step: 1
    mimetype:
      name: MIME type
      description: format to save the image as
      required: true
      default: image/png
      example: image/png
      selector:
        select:
          options:
          - image/png
          - image/jpeg
