draw:
  name: Draw
  description: |-
    Generate a picture.
    The response variable will contain at least two keys: data holds the base64-encoded data in the format of your choice, and mimetype holds the MIME type of the data (prior to base64 encoding).
  fields:
    payload:
      name: Payload
      description: |-
        List of drawing commands.
        See [the reference](https://github.com/Rudd-O/hass-simple-image-raster?tab=readme-ov-file#payload-element-examples) for information on commands, and [the drawing tool](https://eigger.github.io/Niimbot_Payload_Editor.html) for interactive generation of commands.
      required: true
      example: |
        - type: text
          value: Hello World!
          x: 5
          y: 5
          size: 40
      selector:
        object:
    rotate:
      name: Rotate
      description: "Picture rotation in degrees (0, 90, 180, 270), default: 0"
      required: false
      example: '0'
      default: 0
      selector:
        number:
          min: 0
          max: 270
          step: 90
    width:
      name: Width
      description: Width of picture in pixels.
      required: true
      example: 400
      selector:
        number:
          min: 10
          max: 4096
          step: 1
    height:
      name: Height
      description: Height of picture in pixels.
      required: true
      example: 240
      selector:
        number:
          min: 10
          max: 4096
          step: 1
    mimetype:
      name: MIME type
      description: Format to save the image as.
      required: true
      default: image/png
      example: image/png
      selector:
        select:
          options:
          - image/png
          - image/jpeg
          - application/pdf
    options:
      name: Image format options
      description: |-
        A dictionary of `name`: `value` to pass to the `Image.save()` function.
        See [integration documentation](https://github.com/Rudd-O/hass-simple-image-raster?tab=readme-ov-file#image-save-options) for more information.
      required: false
      selector:
        object:
